-- AlterTable
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dateOfBirth" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "alternatePhone" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "organizationType" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "businessName" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "tin" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "businessSize" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "contactPerson" TEXT;
